#!/bin/bash
# Ordner Clipboard
xclip &
#autocutsel -s PRIMARY &
# var for session name (to avoid repeated occurences)
sn=Kommando
tmux new-session -s "$sn" -n arbeid -d
tmux new-window -t "$sn":2 -n vim   'vim -c "Calendar -position=tab"'
tmux new-window -t "$sn":3 -n mutt 
tmux new-window -t "$sn":4 -n div
tmux new-window -t "$sn":5 -n info
tmux select-window -t "$sn":3
tmux send-keys -t "mutt" "Mutt" Enter
tmux select-window -t "$sn":5
tmux split-window -h -p 25 
tmux split-window -v -p 75 
tmux select-window -t "$sn":1
tmux -2 attach-session -t "$sn"
