#!/bin/bash
#Lagrer ei temp-fil
temp=$(mktemp -t temp.XXXXXX)
#Finner modifiserte filer
pacman -Qii | awk '/\[modified\]/ {print $(NF - 1)}' >tmp
#Kopierer disse
IFS=$'\n'
for fil in $(cat $temp)
do
	sudo cp $fil /home/tor/Dokumenter/Data/etc_endra/
done
sudo chmod -R a=rwX /home/tor/Dokumenter/Data/etc_endra/
