#!/bin/bash

# Script til å kjøre før snapshot av home

#Oppretter liste over installerte pakker og lagrer den så den blir kopiert til serveren
pacman -Qqne > /home/tor/Dokumenter/Data/Konfigurasjoner/pkg.list

#Samme for AUR-pakker
pacman -Qqm > /home/tor/Dokumenter/Data/Konfigurasjoner/aur.list 

#Oppretter liste over endra /etc-filer

#Lagrer ei temp-fil
temp=$(mktemp -t temp.XXXXXX)

#Finner modifiserte filer
comm -13 <(pacman -Qlq | sort) <(find /etc -type f | sort) > $temp
#Skal filtrere bort disse seinere
prefix="/etc/ca-certificates/"
#pacman -Qii | awk '/\[modified\]/ {print $(NF - 1)}' > tmp
#Kopierer disse
IFS=$'\n'
for fil in $(cat $temp)
do
	if [[ "$fil" != "$prefix"* ]]; then
		sudo cp $fil /home/tor/Dokumenter/Data/etc_endra/
	fi
done
sudo chmod -R a=rwX /home/tor/Dokumenter/Data/etc_endra/
