#!/bin/bash

# Lagrer STDOUT og STDERR

exec 3>&1
exec 4>&2

#Oppretter filer
DATO=$(date '+%d%m%y')
LOGG=/home/tor/Scripts/Logg/logg_$DATO
FEIL=/home/tor/Scripts/Logg/feil_$DATO

#Omdirigerer utskrift og feilmedlinger til filene
exec 1>$LOGG
exec 2>$FEIL

#Oppretter liste over installerte pakker og lagrer den så den blir kopiert til serveren
pacman -Qqne > /home/tor/Dokumenter/Data/Pakkelister/pkg.list

#Oppretter liste over endra /etc-filer
temp=$(mktemp -t temp.XXXXXX)
sudo pacman -Qii | awk '/^MODIFIED/ {print $2}' >$temp
#Kopierer disse
IFS=$'\n'
for fil in $(cat $temp)
do
	sudo cp $fil /home/tor/Dokumenter/Data/etc_endra/
done
sudo chmod -R a=rwX /home/tor/Dokumenter/Data/etc_endra/

#Synkroniserer med serveren

rsync -vaz -e ssh /home/tor/Dokumenter/ tor@192.168.10.100:/felles/tor_filer/dokumenter
rsync -vaz -e ssh /home/tor/Latex/ tor@192.168.10.100:/felles/tor_filer/latex
rsync -vaz -e ssh /home/tor/Bridge/ tor@192.168.10.100:/felles/bridge
rsync -vaz -e ssh /home/tor/Musikk/ tor@192.168.10.100:/felles/musikk
rsync -vaz -e ssh /home/tor/Bilder/ tor@192.168.10.100:/felles/tor_filer/bilder
rsync -vaz -e ssh /home/tor/Bilder_fra_Inger/ tor@192.168.10.100:/felles/Bilder_fra_Inger
rsync -vaz -e ssh /home/tor/Mail/ tor@192.168.10.100:/felles/tor_filer/mail

#Tilbake til STDOUT og STDERR
exec 1>&3
exec 2>&4
